[versions]
agp = "8.13.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
soraEditorVersion = "0.24.2"
kotlin-coroutines = "1.10.2"
antlr4 = "4.13.2"
gson = "2.13.2"

lsp4jVersion = "0.24.0"
exposedVersion = "0.37.3"
jmhVersion = "1.37"
guavaVersion = "33.4.0-jre"
fernFlowerVersion = "243.22562.218"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
soraEditor = { group = "io.github.rosemoe" , name = "editor" , version.ref = "soraEditorVersion" }
soraEditor-treesitter = { group = "io.github.rosemoe" , name = "language-treesitter" , version.ref = "soraEditorVersion" }
soraEditor-textmate = { group = "io.github.rosemoe"  , name = "language-textmate" , version.ref = "soraEditorVersion" }
soraEditor-lsp = { group = "io.github.rosemoe" , name = "editor-lsp" , version.ref = "soraEditorVersion" }

# Kotlin compiler embeddable for Kotlin LSP
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-scripting-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable", version.ref = "kotlin" }

# Kotlin Language Server dependencies
org-eclipse-lsp4j-lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4jVersion" }
org-eclipse-lsp4j-jsonrpc = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc", version.ref = "lsp4jVersion" }
com-jetbrains-intellij-java-decompiler = { module = "com.jetbrains.intellij.java:java-decompiler-engine", version = "232.10227.8" }
org-jetbrains-exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposedVersion" }
org-jetbrains-exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposedVersion" }
org-jetbrains-exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposedVersion" }
com-h2database-h2 = { module = "com.h2database:h2", version = "2.2.224" }
com-github-fwcd-ktfmt = { module = "com.facebook:ktfmt", version = "0.58" }
com-beust-jcommander = { module = "com.beust:jcommander", version = "1.82" }
org-xerial-sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version = "3.45.0.0" }
hamcrest-all = { module = "org.hamcrest:hamcrest-all", version = "1.3" }
junit-junit = { module = "junit:junit", version = "4.13.2" }
org-openjdk-jmh-core = { module = "org.openjdk.jmh:jmh-core", version = "1.37" }
org-openjdk-jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version = "1.37" }
org-jetbrains-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
org-jetbrains-kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }
org-jetbrains-kotlin-ktscompiler = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler", version.ref = "kotlin" }
org-jetbrains-kotlin-kts-jvm-host-unshaded = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm-host-unshaded", version.ref = "kotlin" }
org-jetbrains-kotlin-sam-with-receiver-compiler-plugin = { module = "org.jetbrains.kotlin:sam-with-receiver-compiler-plugin", version.ref = "kotlin" }
org-jetbrains-kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
org-jetbrains-kotlin-kotlin-scripting-jvm-host = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm-host", version.ref = "kotlin" }
com-google-guava-guava = { module = "com.google.guava:guava", version = "guavaVersion" }

# Google
material = { module = "com.google.android.material:material", version.ref = "material" }
google-gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
google-guava = { module = "com.google.guava:guava", version = "32.1.3-android" }
google-auto-value-annotations = { module = "com.google.auto.value:auto-value-annotations", version = "1.10.4" }
google-auto-value-ap = { module = "com.google.auto.value:auto-value", version = "1.10.4" }
google-auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version = "1.1.1" }
google-auto-service = { module = "com.google.auto.service:auto-service", version = "1.1.1" }
google-protobuf = { module = "com.google.protobuf:protobuf-javalite", version = "3.25.3" }
google-java-format = { module = "com.google.googlejavaformat:google-java-format", version = "1.20.0" }
google-flexbox = { module = "com.google.android.flexbox:flexbox", version = "3.0.0" }

# Bytecode utilities
asm = { module = "org.ow2.asm:asm", version = "9.7.1" }

#Common
common-antlr4 = { module = "org.antlr:antlr4", version.ref = "antlr4" }
common-antlr4-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr4" }
common-jsonrpc = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc", version.ref = "lsp4jVersion" }